spring:
  # DATABASE
  datasource:
    url: ${DB_URL}
    driverClassName: com.mysql.cj.jdbc.Driver
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  # JPA
  jpa:
    properties:
      hibernate:
        # INIT
        ddl-auto: create-drop
        # DEV
        # ddl-auto: update # Only 'create' when init
        show_sql: true
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true

# JWT
jwt:
  secret:
    key:
      ${JWT_KEY}